import os
import uuid
from datetime import datetime

EXPORT_DIR = "static/exports"
os.makedirs(EXPORT_DIR, exist_ok=True)


def export_pdf(text: str, session_token: str = "") -> str:
    """Generate a formatted PDF transcript and return its file path."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib import colors

    filename = f"transcript_{uuid.uuid4().hex[:8]}.pdf"
    filepath = os.path.join(EXPORT_DIR, filename)

    doc    = SimpleDocTemplate(filepath, pagesize=A4,
                               leftMargin=2*cm, rightMargin=2*cm,
                               topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", parent=styles["Title"],
                                 fontSize=18, spaceAfter=6, textColor=colors.HexColor("#1E3A5F"))
    sub_style   = ParagraphStyle("Sub",   parent=styles["Normal"],
                                 fontSize=10, textColor=colors.grey, spaceAfter=12)
    body_style  = ParagraphStyle("Body",  parent=styles["Normal"],
                                 fontSize=13, leading=20, spaceAfter=12)

    date_str = datetime.now().strftime("%d %B %Y, %I:%M %p")
    story    = [
        Paragraph("Sign Language Session Transcript", title_style),
        Paragraph(f"Exported on: {date_str}  |  Session: {session_token[:12] or 'N/A'}", sub_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0891B2")),
        Spacer(1, 0.4*cm),
        Paragraph(text.strip() or "(No text recognized in this session)", body_style),
        Spacer(1, 0.6*cm),
        HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey),
        Spacer(1, 0.2*cm),
        Paragraph("Generated by Sign Language to Audio & Text Conversion System — PEC, Vaniyambadi",
                  ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey)),
    ]
    doc.build(story)
    print(f"[Export] PDF saved: {filepath}")
    return filepath


def export_word(text: str, session_token: str = "") -> str:
    """Generate a formatted Word (.docx) transcript and return its file path."""
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    filename = f"transcript_{uuid.uuid4().hex[:8]}.docx"
    filepath = os.path.join(EXPORT_DIR, filename)

    doc  = Document()
    date_str = datetime.now().strftime("%d %B %Y, %I:%M %p")

    # Title
    title_para = doc.add_heading("Sign Language Session Transcript", level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title_para.runs:
        run.font.color.rgb = RGBColor(0x1E, 0x3A, 0x5F)

    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run  = meta.add_run(f"Exported on: {date_str}  |  Session: {session_token[:12] or 'N/A'}")
    run.font.size  = Pt(10)
    run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_paragraph()  # spacer

    # Transcript body
    body = doc.add_paragraph(text.strip() or "(No text recognized in this session)")
    body.runs[0].font.size = Pt(13)

    doc.add_paragraph()
    footer_para = doc.add_paragraph(
        "Generated by Sign Language to Audio & Text Conversion System — PEC, Vaniyambadi")
    footer_para.runs[0].font.size = Pt(8)
    footer_para.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.save(filepath)
    print(f"[Export] Word saved: {filepath}")
    return filepath
